services:
  - type: web
    name: dynamo-license-server
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python license_server.py"
    disk:
      name: data
      mountPath: /mnt/data
      sizeGB: 1
