
services:
  - type: web
    name: license-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python license_server.py"
    envVars: []
    autoDeploy: true
    region: oregon
    branch: main
    runtime: python
